### ISSUE TITLE
Incompatible options with other styles

### ISSUE THREAD

**Issue by e-kwsm** [josephwright/biblatex-science#1]
Sometimes I play with biblatex styles—switch and compare them.
I noticed some of options are incompatible, namely a style supports them but other doesn't.

Here is the list of options and styles.

| | `article-title` | `articletitle` | `chaptertitle` | `doi` | `eprint` | `intitle` | `isbn` | `pageranges` | `related` |
|--------------------|---|---|---|---|---|---|---|---|---|
| `chem-acs.bbx`     | n | y | y | y | y | n | y | y | y |
| `chem-angew.bbx`   | n | y | y | y | n | n | y | y | y |
| `chem-biochem.bbx` | n | y | y | y | y | n | y | y | y |
| `chem-rsc.bbx`     | n | y | y | y | n | n | y | y | y |
| `nature.bbx`       | n | y | n | n | y | y | y | n | n |
| `science.bbx`      | y | n | n | n | y | n | y | n | n |
| `phys.bbx`         | n | y | y | n | n | n | y | y | y |

Particularly, only `biblatex-science` provides `article-type`, while the other packages—`biblatex-chem`, `biblatex-nature`, and `biblatex-phys`—provides `articletype`.

Would you support `articletype` option?

**Comment by josephwright** [comment]
I'll tidy up a bit here: I think with `biblatex-science` I was aiming for what I think is the better long-term naming.

**Comment by josephwright** [comment]
Commits https://github.com/josephwright/biblatex-science/commit/a05c62b7d4b06747a6979ca82d978188dbeac696, https://github.com/josephwright/biblatex-science/commit/58c81f1ae321063c58b2faf4eb13101e8afc22d3 and https://github.com/josephwright/biblatex-science/commit/9ad705a54d374d8e5711aebfa0f8f768a297c321 should bring the Science style better in to line with the standard approach. I'll leave the issue open at present, and will look to tidy up other stuff in my '`biblatex` bundles' over the coming days.

**Comment by josephwright** [comment]
Hopefully this is much tidier for the set of styles now. I've not added `pagerange` for everything: it's never come up for the `science`/`nature` styles. Similarly, `intitle` is pretty specialised: I don't think it applies to any styles other than the `nature` one.

**Comment by e-kwsm** [comment]
Thank you!
